// ─────────────────────────────────────────────────────────────────────────────
// handlers.ts  —  generated by MCPify
//
// Fill in the implementation for each tool handler.
// These are called by server.ts when an AI agent invokes a tool.
// ─────────────────────────────────────────────────────────────────────────────

import type { ToolInputs } from './schemas.js';
import * as __mcpify_getOrderById_0 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_getOrdersByStatus_1 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_countOrdersByStatus_2 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_searchOrders_3 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_refundOrder_4 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_cancelOrder_5 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_updateOrderStatus_6 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_assignOrderToAgent_7 from '../examples/ecommerce-saas/src/services/orders.js';
import * as __mcpify_listTicketsByStatus_8 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_getTicketById_9 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_searchTickets_10 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_createSupportRequest_11 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_replyToTicket_12 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_assignTicket_13 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_escalateTicket_14 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_resolveTicket_15 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_sendMessageToCustomer_16 from '../examples/ecommerce-saas/src/services/support.js';
import * as __mcpify_getUserByEmail_17 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_getUserById_18 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_listUsers_19 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_searchUsers_20 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_registerUser_21 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_authenticateUser_22 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_updateUserRole_23 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_suspendUser_24 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_initiatePasswordReset_25 from '../examples/ecommerce-saas/src/services/users.js';
import * as __mcpify_inviteTeamMember_26 from '../examples/ecommerce-saas/src/services/users.js';

function resolveExport(moduleExports: unknown, exportName: string): (...args: any[]) => unknown {
  const record = moduleExports as Record<string, any>;
  const value = record[exportName] ?? record.default?.[exportName];
  if (typeof value !== 'function') {
    throw new Error(`source export is not callable: ${exportName}`);
  }
  return value;
}

/** Retrieves a single order by its ID. */
export async function handle_getOrderById(args: ToolInputs['getOrderById']): Promise<unknown> {
  // Available: orderId: string
  return await resolveExport(__mcpify_getOrderById_0, "getOrderById")(args["orderId"] as any);
}

/** Lists all orders with an optional status filter and pagination. */
export async function handle_getOrdersByStatus(args: ToolInputs['getOrdersByStatus']): Promise<unknown> {
  // Available: status: import("C:/Users/amarn/OneDrive/Desktop/kochi/MCPify/examples/ecommerce-saas/src/services/orders").OrderStatus, limit: number, offset: number
  return await resolveExport(__mcpify_getOrdersByStatus_1, "getOrdersByStatus")(args["status"] as any, args["limit"] as any, args["offset"] as any);
}

/** Returns the total count of orders grouped by status. */
export async function handle_countOrdersByStatus(): Promise<unknown> {
  return await resolveExport(__mcpify_countOrdersByStatus_2, "countOrdersByStatus")();
}

/** Searches orders by customer email or name. */
export async function handle_searchOrders(args: ToolInputs['searchOrders']): Promise<unknown> {
  // Available: query: string
  return await resolveExport(__mcpify_searchOrders_3, "searchOrders")(args["query"] as any);
}

/** Issues a full or partial refund for an order. */
export async function handle_refundOrder(args: ToolInputs['refundOrder']): Promise<unknown> {
  // Available: orderId: string, amount: number | undefined
  return await resolveExport(__mcpify_refundOrder_4, "refundOrder")(args["orderId"] as any, args["amount"] as any);
}

/** Cancels a pending or processing order. */
export async function handle_cancelOrder(args: ToolInputs['cancelOrder']): Promise<unknown> {
  // Available: orderId: string, reason: string
  return await resolveExport(__mcpify_cancelOrder_5, "cancelOrder")(args["orderId"] as any, args["reason"] as any);
}

/** Updates the fulfillment status of an order. */
export async function handle_updateOrderStatus(args: ToolInputs['updateOrderStatus']): Promise<unknown> {
  // Available: orderId: string, status: import("C:/Users/amarn/OneDrive/Desktop/kochi/MCPify/examples/ecommerce-saas/src/services/orders").OrderStatus
  return await resolveExport(__mcpify_updateOrderStatus_6, "updateOrderStatus")(args["orderId"] as any, args["status"] as any);
}

/** Assigns an order to a fulfilment agent. */
export async function handle_assignOrderToAgent(args: ToolInputs['assignOrderToAgent']): Promise<unknown> {
  // Available: orderId: string, agentId: string
  return await resolveExport(__mcpify_assignOrderToAgent_7, "assignOrderToAgent")(args["orderId"] as any, args["agentId"] as any);
}

/** List support tickets filtered by status. */
export async function handle_listTicketsByStatus(args: ToolInputs['listTicketsByStatus']): Promise<unknown> {
  // Available: status: import("C:/Users/amarn/OneDrive/Desktop/kochi/MCPify/examples/ecommerce-saas/src/services/support").TicketStatus
  return await resolveExport(__mcpify_listTicketsByStatus_8, "listTicketsByStatus")(args["status"] as any);
}

/** Get a single support ticket by ID. */
export async function handle_getTicketById(args: ToolInputs['getTicketById']): Promise<unknown> {
  // Available: ticketId: string
  return await resolveExport(__mcpify_getTicketById_9, "getTicketById")(args["ticketId"] as any);
}

/** Search tickets by keyword in subject or body. */
export async function handle_searchTickets(args: ToolInputs['searchTickets']): Promise<unknown> {
  // Available: query: string
  return await resolveExport(__mcpify_searchTickets_10, "searchTickets")(args["query"] as any);
}

/** Creates a new support ticket. */
export async function handle_createSupportRequest(args: ToolInputs['createSupportRequest']): Promise<unknown> {
  // Available: customerId: string, subject: string, body: string, orderId: string | undefined
  return await resolveExport(__mcpify_createSupportRequest_11, "createSupportRequest")(args["customerId"] as any, args["subject"] as any, args["body"] as any, args["orderId"] as any);
}

/** Sends a reply message to a support ticket. */
export async function handle_replyToTicket(args: ToolInputs['replyToTicket']): Promise<unknown> {
  // Available: ticketId: string, message: string
  return await resolveExport(__mcpify_replyToTicket_12, "replyToTicket")(args["ticketId"] as any, args["message"] as any);
}

/** Assigns a ticket to a support agent. */
export async function handle_assignTicket(args: ToolInputs['assignTicket']): Promise<unknown> {
  // Available: ticketId: string, agentId: string
  return await resolveExport(__mcpify_assignTicket_13, "assignTicket")(args["ticketId"] as any, args["agentId"] as any);
}

/** Escalates a ticket to a higher-tier agent. */
export async function handle_escalateTicket(args: ToolInputs['escalateTicket']): Promise<unknown> {
  // Available: ticketId: string, reason: string
  return await resolveExport(__mcpify_escalateTicket_14, "escalateTicket")(args["ticketId"] as any, args["reason"] as any);
}

/** Marks a support ticket as resolved. */
export async function handle_resolveTicket(args: ToolInputs['resolveTicket']): Promise<unknown> {
  // Available: ticketId: string, resolution: string
  return await resolveExport(__mcpify_resolveTicket_15, "resolveTicket")(args["ticketId"] as any, args["resolution"] as any);
}

/** Sends a direct message to a customer. */
export async function handle_sendMessageToCustomer(args: ToolInputs['sendMessageToCustomer']): Promise<unknown> {
  // Available: customerId: string, message: string
  return await resolveExport(__mcpify_sendMessageToCustomer_16, "sendMessageToCustomer")(args["customerId"] as any, args["message"] as any);
}

/** Find a user by their email address. */
export async function handle_getUserByEmail(args: ToolInputs['getUserByEmail']): Promise<unknown> {
  // Available: email: string
  return await resolveExport(__mcpify_getUserByEmail_17, "getUserByEmail")(args["email"] as any);
}

/** Get a user by ID. */
export async function handle_getUserById(args: ToolInputs['getUserById']): Promise<unknown> {
  // Available: userId: string
  return await resolveExport(__mcpify_getUserById_18, "getUserById")(args["userId"] as any);
}

/** List all users with optional role filter. */
export async function handle_listUsers(args: ToolInputs['listUsers']): Promise<unknown> {
  // Available: role: "customer" | "admin" | "agent" | undefined
  return await resolveExport(__mcpify_listUsers_19, "listUsers")(args["role"] as any);
}

/** Search users by name or email fragment. */
export async function handle_searchUsers(args: ToolInputs['searchUsers']): Promise<unknown> {
  // Available: query: string
  return await resolveExport(__mcpify_searchUsers_20, "searchUsers")(args["query"] as any);
}

/** Registers a new user account. */
export async function handle_registerUser(args: ToolInputs['registerUser']): Promise<unknown> {
  // Available: email: string, name: string, password: string
  return await resolveExport(__mcpify_registerUser_21, "registerUser")(args["email"] as any, args["name"] as any, args["password"] as any);
}

/** Authenticates a user and returns a session token. */
export async function handle_authenticateUser(args: ToolInputs['authenticateUser']): Promise<unknown> {
  // Available: email: string, password: string
  return await resolveExport(__mcpify_authenticateUser_22, "authenticateUser")(args["email"] as any, args["password"] as any);
}

/** Updates a user's role (admin action). */
export async function handle_updateUserRole(args: ToolInputs['updateUserRole']): Promise<unknown> {
  // Available: userId: string, newRole: "customer" | "admin" | "agent"
  return await resolveExport(__mcpify_updateUserRole_23, "updateUserRole")(args["userId"] as any, args["newRole"] as any);
}

/** Suspends a user account. */
export async function handle_suspendUser(args: ToolInputs['suspendUser']): Promise<unknown> {
  // Available: userId: string, reason: string
  return await resolveExport(__mcpify_suspendUser_24, "suspendUser")(args["userId"] as any, args["reason"] as any);
}

/** Sends a password reset email. */
export async function handle_initiatePasswordReset(args: ToolInputs['initiatePasswordReset']): Promise<unknown> {
  // Available: email: string
  return await resolveExport(__mcpify_initiatePasswordReset_25, "initiatePasswordReset")(args["email"] as any);
}

/** Invites a new team member by email. */
export async function handle_inviteTeamMember(args: ToolInputs['inviteTeamMember']): Promise<unknown> {
  // Available: email: string, role: "customer" | "admin" | "agent"
  return await resolveExport(__mcpify_inviteTeamMember_26, "inviteTeamMember")(args["email"] as any, args["role"] as any);
}

type GeneratedHandler = (args: Record<string, unknown>) => Promise<unknown>;

const TOOL_HANDLERS: Record<string, GeneratedHandler> = {
  "getOrderById": handle_getOrderById as GeneratedHandler,
  "getOrdersByStatus": handle_getOrdersByStatus as GeneratedHandler,
  "countOrdersByStatus": handle_countOrdersByStatus as GeneratedHandler,
  "searchOrders": handle_searchOrders as GeneratedHandler,
  "refundOrder": handle_refundOrder as GeneratedHandler,
  "cancelOrder": handle_cancelOrder as GeneratedHandler,
  "updateOrderStatus": handle_updateOrderStatus as GeneratedHandler,
  "assignOrderToAgent": handle_assignOrderToAgent as GeneratedHandler,
  "listTicketsByStatus": handle_listTicketsByStatus as GeneratedHandler,
  "getTicketById": handle_getTicketById as GeneratedHandler,
  "searchTickets": handle_searchTickets as GeneratedHandler,
  "createSupportRequest": handle_createSupportRequest as GeneratedHandler,
  "replyToTicket": handle_replyToTicket as GeneratedHandler,
  "assignTicket": handle_assignTicket as GeneratedHandler,
  "escalateTicket": handle_escalateTicket as GeneratedHandler,
  "resolveTicket": handle_resolveTicket as GeneratedHandler,
  "sendMessageToCustomer": handle_sendMessageToCustomer as GeneratedHandler,
  "getUserByEmail": handle_getUserByEmail as GeneratedHandler,
  "getUserById": handle_getUserById as GeneratedHandler,
  "listUsers": handle_listUsers as GeneratedHandler,
  "searchUsers": handle_searchUsers as GeneratedHandler,
  "registerUser": handle_registerUser as GeneratedHandler,
  "authenticateUser": handle_authenticateUser as GeneratedHandler,
  "updateUserRole": handle_updateUserRole as GeneratedHandler,
  "suspendUser": handle_suspendUser as GeneratedHandler,
  "initiatePasswordReset": handle_initiatePasswordReset as GeneratedHandler,
  "inviteTeamMember": handle_inviteTeamMember as GeneratedHandler
};


// ── Workflow handlers ─────────────────────────

