// Auto-generated by MCPify — do not edit manually.
// Re-run `npx mcpify` to regenerate after code changes.

export interface McpifyTool {
  name:        string;
  description: string;
  permission:  'SAFE' | 'REQUIRES_CONFIRMATION' | 'BLOCKED' | 'UNKNOWN';
  source:      string;
  inputSchema: {
    type:       'object';
    properties: Record<string, { type: string; description?: string }>;
    required:   string[];
  };
}

/**
 * Retrieves a single order by its ID.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "getOrderById" is non-destructive and may be executed autonomously by AI agents.
 */
export const getOrderByIdTool = {
  name:        'getOrderById',
  description: "Retrieves a single order by its ID.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        orderId: { type: 'string', description: 'orderId' }
    },
    required: ["orderId"],
  },
} satisfies McpifyTool;

/**
 * Lists all orders with an optional status filter and pagination.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "getOrdersByStatus" is non-destructive and may be executed autonomously by AI agents.
 */
export const getOrdersByStatusTool = {
  name:        'getOrdersByStatus',
  description: "Lists all orders with an optional status filter and pagination.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        status: { type: 'string', description: 'status' },
        limit: { type: 'number', description: 'limit' },
        offset: { type: 'number', description: 'offset' }
    },
    required: ["status","limit","offset"],
  },
} satisfies McpifyTool;

/**
 * Returns the total count of orders grouped by status.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "countOrdersByStatus" is non-destructive and may be executed autonomously by AI agents.
 */
export const countOrdersByStatusTool = {
  name:        'countOrdersByStatus',
  description: "Returns the total count of orders grouped by status.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        // no parameters
    },
    required: [],
  },
} satisfies McpifyTool;

/**
 * Searches orders by customer email or name.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "searchOrders" is non-destructive and may be executed autonomously by AI agents.
 */
export const searchOrdersTool = {
  name:        'searchOrders',
  description: "Searches orders by customer email or name.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        query: { type: 'string', description: 'query' }
    },
    required: ["query"],
  },
} satisfies McpifyTool;

/**
 * Issues a full or partial refund for an order.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "refundOrder" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const refundOrderTool = {
  name:        'refundOrder',
  description: "Issues a full or partial refund for an order.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        orderId: { type: 'string', description: 'orderId' },
        amount: { type: 'string', description: 'amount' }
    },
    required: ["orderId","amount"],
  },
} satisfies McpifyTool;

/**
 * Cancels a pending or processing order.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "cancelOrder" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const cancelOrderTool = {
  name:        'cancelOrder',
  description: "Cancels a pending or processing order.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        orderId: { type: 'string', description: 'orderId' },
        reason: { type: 'string', description: 'reason' }
    },
    required: ["orderId","reason"],
  },
} satisfies McpifyTool;

/**
 * Updates the fulfillment status of an order.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "updateOrderStatus" is non-destructive and may be executed autonomously by AI agents.
 */
export const updateOrderStatusTool = {
  name:        'updateOrderStatus',
  description: "Updates the fulfillment status of an order.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        orderId: { type: 'string', description: 'orderId' },
        status: { type: 'string', description: 'status' }
    },
    required: ["orderId","status"],
  },
} satisfies McpifyTool;

/**
 * Assigns an order to a fulfilment agent.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "assignOrderToAgent" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const assignOrderToAgentTool = {
  name:        'assignOrderToAgent',
  description: "Assigns an order to a fulfilment agent.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        orderId: { type: 'string', description: 'orderId' },
        agentId: { type: 'string', description: 'agentId' }
    },
    required: ["orderId","agentId"],
  },
} satisfies McpifyTool;

/**
 * List support tickets filtered by status.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "listTicketsByStatus" is non-destructive and may be executed autonomously by AI agents.
 */
export const listTicketsByStatusTool = {
  name:        'listTicketsByStatus',
  description: "List support tickets filtered by status.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        status: { type: 'string', description: 'status' }
    },
    required: ["status"],
  },
} satisfies McpifyTool;

/**
 * Get a single support ticket by ID.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "getTicketById" is non-destructive and may be executed autonomously by AI agents.
 */
export const getTicketByIdTool = {
  name:        'getTicketById',
  description: "Get a single support ticket by ID.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        ticketId: { type: 'string', description: 'ticketId' }
    },
    required: ["ticketId"],
  },
} satisfies McpifyTool;

/**
 * Search tickets by keyword in subject or body.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "searchTickets" is non-destructive and may be executed autonomously by AI agents.
 */
export const searchTicketsTool = {
  name:        'searchTickets',
  description: "Search tickets by keyword in subject or body.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        query: { type: 'string', description: 'query' }
    },
    required: ["query"],
  },
} satisfies McpifyTool;

/**
 * Creates a new support ticket.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "createSupportRequest" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const createSupportRequestTool = {
  name:        'createSupportRequest',
  description: "Creates a new support ticket.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        customerId: { type: 'string', description: 'customerId' },
        subject: { type: 'string', description: 'subject' },
        body: { type: 'string', description: 'body' },
        orderId: { type: 'string', description: 'orderId' }
    },
    required: ["customerId","subject","body","orderId"],
  },
} satisfies McpifyTool;

/**
 * Sends a reply message to a support ticket.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "replyToTicket" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const replyToTicketTool = {
  name:        'replyToTicket',
  description: "Sends a reply message to a support ticket.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        ticketId: { type: 'string', description: 'ticketId' },
        message: { type: 'string', description: 'message' }
    },
    required: ["ticketId","message"],
  },
} satisfies McpifyTool;

/**
 * Assigns a ticket to a support agent.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "assignTicket" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const assignTicketTool = {
  name:        'assignTicket',
  description: "Assigns a ticket to a support agent.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        ticketId: { type: 'string', description: 'ticketId' },
        agentId: { type: 'string', description: 'agentId' }
    },
    required: ["ticketId","agentId"],
  },
} satisfies McpifyTool;

/**
 * Escalates a ticket to a higher-tier agent.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "escalateTicket" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const escalateTicketTool = {
  name:        'escalateTicket',
  description: "Escalates a ticket to a higher-tier agent.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        ticketId: { type: 'string', description: 'ticketId' },
        reason: { type: 'string', description: 'reason' }
    },
    required: ["ticketId","reason"],
  },
} satisfies McpifyTool;

/**
 * Marks a support ticket as resolved.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "resolveTicket" is non-destructive and may be executed autonomously by AI agents.
 */
export const resolveTicketTool = {
  name:        'resolveTicket',
  description: "Marks a support ticket as resolved.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        ticketId: { type: 'string', description: 'ticketId' },
        resolution: { type: 'string', description: 'resolution' }
    },
    required: ["ticketId","resolution"],
  },
} satisfies McpifyTool;

/**
 * Sends a direct message to a customer.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "sendMessageToCustomer" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const sendMessageToCustomerTool = {
  name:        'sendMessageToCustomer',
  description: "Sends a direct message to a customer.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        customerId: { type: 'string', description: 'customerId' },
        message: { type: 'string', description: 'message' }
    },
    required: ["customerId","message"],
  },
} satisfies McpifyTool;

/**
 * Find a user by their email address.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "getUserByEmail" is non-destructive and may be executed autonomously by AI agents.
 */
export const getUserByEmailTool = {
  name:        'getUserByEmail',
  description: "Find a user by their email address.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        email: { type: 'string', description: 'email' }
    },
    required: ["email"],
  },
} satisfies McpifyTool;

/**
 * Get a user by ID.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "getUserById" is non-destructive and may be executed autonomously by AI agents.
 */
export const getUserByIdTool = {
  name:        'getUserById',
  description: "Get a user by ID.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        userId: { type: 'string', description: 'userId' }
    },
    required: ["userId"],
  },
} satisfies McpifyTool;

/**
 * List all users with optional role filter.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "listUsers" is non-destructive and may be executed autonomously by AI agents.
 */
export const listUsersTool = {
  name:        'listUsers',
  description: "List all users with optional role filter.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        role: { type: 'string', description: 'role' }
    },
    required: ["role"],
  },
} satisfies McpifyTool;

/**
 * Search users by name or email fragment.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "searchUsers" is non-destructive and may be executed autonomously by AI agents.
 */
export const searchUsersTool = {
  name:        'searchUsers',
  description: "Search users by name or email fragment.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        query: { type: 'string', description: 'query' }
    },
    required: ["query"],
  },
} satisfies McpifyTool;

/**
 * Registers a new user account.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "registerUser" is non-destructive and may be executed autonomously by AI agents.
 */
export const registerUserTool = {
  name:        'registerUser',
  description: "Registers a new user account.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        email: { type: 'string', description: 'email' },
        name: { type: 'string', description: 'name' },
        password: { type: 'string', description: 'password' }
    },
    required: ["email","name","password"],
  },
} satisfies McpifyTool;

/**
 * Authenticates a user and returns a session token.
 *
 * @permission SAFE
 * @source     backend
 * @safety     "authenticateUser" is non-destructive and may be executed autonomously by AI agents.
 */
export const authenticateUserTool = {
  name:        'authenticateUser',
  description: "Authenticates a user and returns a session token.",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        email: { type: 'string', description: 'email' },
        password: { type: 'string', description: 'password' }
    },
    required: ["email","password"],
  },
} satisfies McpifyTool;

/**
 * Updates a user's role (admin action).
 *
 * @permission SAFE
 * @source     backend
 * @safety     "updateUserRole" is non-destructive and may be executed autonomously by AI agents.
 */
export const updateUserRoleTool = {
  name:        'updateUserRole',
  description: "Updates a user's role (admin action).",
  permission:  'SAFE' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        userId: { type: 'string', description: 'userId' },
        newRole: { type: 'string', description: 'newRole' }
    },
    required: ["userId","newRole"],
  },
} satisfies McpifyTool;

/**
 * Suspends a user account.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "suspendUser" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const suspendUserTool = {
  name:        'suspendUser',
  description: "Suspends a user account.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        userId: { type: 'string', description: 'userId' },
        reason: { type: 'string', description: 'reason' }
    },
    required: ["userId","reason"],
  },
} satisfies McpifyTool;

/**
 * Sends a password reset email.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "initiatePasswordReset" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const initiatePasswordResetTool = {
  name:        'initiatePasswordReset',
  description: "Sends a password reset email.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        email: { type: 'string', description: 'email' }
    },
    required: ["email"],
  },
} satisfies McpifyTool;

/**
 * Invites a new team member by email.
 *
 * @permission REQUIRES_CONFIRMATION
 * @source     backend
 * @safety     "inviteTeamMember" requires explicit user confirmation. The MCP server will reject calls without { "__confirmed": true }.
 */
export const inviteTeamMemberTool = {
  name:        'inviteTeamMember',
  description: "Invites a new team member by email.",
  permission:  'REQUIRES_CONFIRMATION' as const,
  source:      'backend' as const,
  inputSchema: {
    type: 'object' as const,
    properties: {
        email: { type: 'string', description: 'email' },
        role: { type: 'string', description: 'role' }
    },
    required: ["email","role"],
  },
} satisfies McpifyTool;

export const ALL_TOOLS: McpifyTool[] = [
  getOrderByIdTool,
  getOrdersByStatusTool,
  countOrdersByStatusTool,
  searchOrdersTool,
  refundOrderTool,
  cancelOrderTool,
  updateOrderStatusTool,
  assignOrderToAgentTool,
  listTicketsByStatusTool,
  getTicketByIdTool,
  searchTicketsTool,
  createSupportRequestTool,
  replyToTicketTool,
  assignTicketTool,
  escalateTicketTool,
  resolveTicketTool,
  sendMessageToCustomerTool,
  getUserByEmailTool,
  getUserByIdTool,
  listUsersTool,
  searchUsersTool,
  registerUserTool,
  authenticateUserTool,
  updateUserRoleTool,
  suspendUserTool,
  initiatePasswordResetTool,
  inviteTeamMemberTool
];

export const SAFE_TOOLS    = ALL_TOOLS.filter(t => t.permission === 'SAFE');
export const CONFIRM_TOOLS = ALL_TOOLS.filter(t => t.permission === 'REQUIRES_CONFIRMATION');
export const BLOCKED_TOOLS = ALL_TOOLS.filter(t => t.permission === 'BLOCKED');
