// Auto-generated by MCPify — no workflows detected.
export interface McpifyWorkflow {
  name:        string;
  description: string;
  steps:       string[];
  permission:  string;
}

export const ALL_WORKFLOWS: McpifyWorkflow[] = [];
