// Auto-generated by MCPify — do not edit manually.
import { z } from 'zod';

export const getOrderByIdSchema = z.object({
  /** orderId */
  orderId: z.string()
});

export const getOrdersByStatusSchema = z.object({
  /** status */
  status: z.unknown(),
  /** limit */
  limit: z.number(),
  /** offset */
  offset: z.number()
});

export const countOrdersByStatusSchema = z.object({});

export const searchOrdersSchema = z.object({
  /** query */
  query: z.string()
});

export const refundOrderSchema = z.object({
  /** orderId */
  orderId: z.string(),
  /** amount */
  amount: z.enum(['number', 'undefined'])
});

export const cancelOrderSchema = z.object({
  /** orderId */
  orderId: z.string(),
  /** reason */
  reason: z.string()
});

export const updateOrderStatusSchema = z.object({
  /** orderId */
  orderId: z.string(),
  /** status */
  status: z.unknown()
});

export const assignOrderToAgentSchema = z.object({
  /** orderId */
  orderId: z.string(),
  /** agentId */
  agentId: z.string()
});

export const listTicketsByStatusSchema = z.object({
  /** status */
  status: z.unknown()
});

export const getTicketByIdSchema = z.object({
  /** ticketId */
  ticketId: z.string()
});

export const searchTicketsSchema = z.object({
  /** query */
  query: z.string()
});

export const createSupportRequestSchema = z.object({
  /** customerId */
  customerId: z.string(),
  /** subject */
  subject: z.string(),
  /** body */
  body: z.string(),
  /** orderId */
  orderId: z.enum(['string', 'undefined'])
});

export const replyToTicketSchema = z.object({
  /** ticketId */
  ticketId: z.string(),
  /** message */
  message: z.string()
});

export const assignTicketSchema = z.object({
  /** ticketId */
  ticketId: z.string(),
  /** agentId */
  agentId: z.string()
});

export const escalateTicketSchema = z.object({
  /** ticketId */
  ticketId: z.string(),
  /** reason */
  reason: z.string()
});

export const resolveTicketSchema = z.object({
  /** ticketId */
  ticketId: z.string(),
  /** resolution */
  resolution: z.string()
});

export const sendMessageToCustomerSchema = z.object({
  /** customerId */
  customerId: z.string(),
  /** message */
  message: z.string()
});

export const getUserByEmailSchema = z.object({
  /** email */
  email: z.string()
});

export const getUserByIdSchema = z.object({
  /** userId */
  userId: z.string()
});

export const listUsersSchema = z.object({
  /** role */
  role: z.enum(['customer', 'admin', 'agent', 'undefined'])
});

export const searchUsersSchema = z.object({
  /** query */
  query: z.string()
});

export const registerUserSchema = z.object({
  /** email */
  email: z.string(),
  /** name */
  name: z.string(),
  /** password */
  password: z.string()
});

export const authenticateUserSchema = z.object({
  /** email */
  email: z.string(),
  /** password */
  password: z.string()
});

export const updateUserRoleSchema = z.object({
  /** userId */
  userId: z.string(),
  /** newRole */
  newRole: z.enum(['customer', 'admin', 'agent'])
});

export const suspendUserSchema = z.object({
  /** userId */
  userId: z.string(),
  /** reason */
  reason: z.string()
});

export const initiatePasswordResetSchema = z.object({
  /** email */
  email: z.string()
});

export const inviteTeamMemberSchema = z.object({
  /** email */
  email: z.string(),
  /** role */
  role: z.enum(['customer', 'admin', 'agent'])
});

export const AdminDashboardSchema = z.object({
  /** {
  onRefund, onApprove, onReject, onPublish,
  onExport, onSearch, onCreateTicket, onSendMessage, onInviteUser, onDeleteRecord,
} */
  {
  onRefund, onApprove, onReject, onPublish,
  onExport, onSearch, onCreateTicket, onSendMessage, onInviteUser, onDeleteRecord,
}: z.unknown()
});

export const CartPageSchema = z.object({
  /** { items, onCheckout, onRemoveItem, onApplyCoupon } */
  { items, onCheckout, onRemoveItem, onApplyCoupon }: z.unknown()
});

export type ToolInputs = {
  getOrderById: z.infer<typeof getOrderByIdSchema>;
  getOrdersByStatus: z.infer<typeof getOrdersByStatusSchema>;
  countOrdersByStatus: z.infer<typeof countOrdersByStatusSchema>;
  searchOrders: z.infer<typeof searchOrdersSchema>;
  refundOrder: z.infer<typeof refundOrderSchema>;
  cancelOrder: z.infer<typeof cancelOrderSchema>;
  updateOrderStatus: z.infer<typeof updateOrderStatusSchema>;
  assignOrderToAgent: z.infer<typeof assignOrderToAgentSchema>;
  listTicketsByStatus: z.infer<typeof listTicketsByStatusSchema>;
  getTicketById: z.infer<typeof getTicketByIdSchema>;
  searchTickets: z.infer<typeof searchTicketsSchema>;
  createSupportRequest: z.infer<typeof createSupportRequestSchema>;
  replyToTicket: z.infer<typeof replyToTicketSchema>;
  assignTicket: z.infer<typeof assignTicketSchema>;
  escalateTicket: z.infer<typeof escalateTicketSchema>;
  resolveTicket: z.infer<typeof resolveTicketSchema>;
  sendMessageToCustomer: z.infer<typeof sendMessageToCustomerSchema>;
  getUserByEmail: z.infer<typeof getUserByEmailSchema>;
  getUserById: z.infer<typeof getUserByIdSchema>;
  listUsers: z.infer<typeof listUsersSchema>;
  searchUsers: z.infer<typeof searchUsersSchema>;
  registerUser: z.infer<typeof registerUserSchema>;
  authenticateUser: z.infer<typeof authenticateUserSchema>;
  updateUserRole: z.infer<typeof updateUserRoleSchema>;
  suspendUser: z.infer<typeof suspendUserSchema>;
  initiatePasswordReset: z.infer<typeof initiatePasswordResetSchema>;
  inviteTeamMember: z.infer<typeof inviteTeamMemberSchema>;
  AdminDashboard: z.infer<typeof AdminDashboardSchema>;
  CartPage: z.infer<typeof CartPageSchema>;
};
